### PR TITLE
Fix default import ufo dependency

### LINKED ISSUE #182: SyntaxError: The requested module 'ufo' does not provide an export named 'default'
### Describe the bug

Error when I use lib version ^2.3.1

### System

- Node.js version: 16.20.1
- NPM version: 9.6.4
- Strapi version: 4.12.5
- Strapi SDK version: 
- Operating system: Mac

### PR DESCRIPTION
**Pull request by flavienrako**
## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other changes (could be a refactor, documentation change ect...)

## Description
Fix "export 'default' (imported as 'ufo') was not found in 'ufo'"

It fixes #182 

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)

### CODE REVIEW

File: src/lib/strapi.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import axios, {
 import defu from "defu";
 import qs from "qs";
 import Cookies from "js-cookie";
-import ufo from "ufo";
+import { cleanDoubleSlashes, joinURL } from "ufo";
```
Comment (Stun3R) [inline src/lib/strapi.ts]: Thanks for your PR ☺️

I already tested this but it will break on webpack application as the .mjs is not listed in module for some reason (nuxt2 application have this issue).

We have 2 choices:
- Document the issue in the doc so user can add the specific config in their webpack but can lead to issue/bug report for misreading the doc
- Make work the use of default so we don't have any issue thanks importing all as module name.

```suggestion
import * as ufo from "ufo";
```

**Review by Stun3R — CHANGES_REQUESTED** [review]

**Comment by Stun3R** [comment]
I'm updating the PR as it is a mandatory hot fix so I can merge & release ASAP

File: src/lib/strapi.ts [hunk 2]
```diff
@@ -66,13 +66,13 @@ export class Strapi {
     // clean url & prefix
     this.options = {
       ..._options,
-      url: ufo.cleanDoubleSlashes(_options?.url),
-      prefix: ufo.cleanDoubleSlashes(_options?.prefix),
+      url: cleanDoubleSlashes(_options?.url),
```
Comment (Stun3R) [inline src/lib/strapi.ts]:
```suggestion
      url: ufo.cleanDoubleSlashes(_options?.url),
```

File: src/lib/strapi.ts [hunk 3]
```diff
@@ -66,13 +66,13 @@ export class Strapi {
...
+      prefix: cleanDoubleSlashes(_options?.prefix),
```
Comment (Stun3R) [inline src/lib/strapi.ts]:
```suggestion
      prefix: ufo.cleanDoubleSlashes(_options?.prefix),
```

File: src/lib/strapi.ts [hunk 4]
```diff
@@ -66,13 +66,13 @@ export class Strapi {
...
     };
 
     // create axios instance
     this.axios = axios.create({
-      baseURL: ufo.joinURL(this.options.url, this.options.prefix),
+      baseURL: joinURL(this.options.url, this.options.prefix),
```
Comment (Stun3R) [inline src/lib/strapi.ts]:
```suggestion
      baseURL: ufo.joinURL(this.options.url, this.options.prefix),
```

File: src/lib/strapi.ts [hunk 5]
```diff
@@ -261,12 +261,7 @@ export class Strapi {
    * @returns string
    */
   public getProviderAuthenticationUrl(provider: StrapiAuthProvider): string {
-    return ufo.joinURL(
-      this.options.url,
-      this.options.prefix,
-      "connect",
-      provider
-    );
+    return joinURL(this.options.url, this.options.prefix, "connect", provider);
```
Comment (Stun3R) [inline src/lib/strapi.ts]:
```suggestion
    return ufo.joinURL(this.options.url, this.options.prefix, "connect", provider);
```

**Review by Stun3R — APPROVED** [review]

**Comment by Stun3R** [comment]
After some try, I kept your change so we are fully using the tree-shaking but this will break old webpack app (nuxt2, vue2...). I will add to the documentation that old webpack app must use the following snippet to load the package:
```js
config.module.rules.push({
    test: /\.mjs$/,
    include: /node_modules/,
    type: 'javascript/auto',
})
```

Example with nuxt2. Add this snippet to your `nuxt.config.js` file:
```js
  build: {
    extend(config) {
      config.module.rules.push({
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto',
      })
    },
  },
```
